### ISSUE TITLE
Repository problems

### ISSUE THREAD

**Issue by komissarovdenis** [AndroidDeveloperLB/AndroidJniBitmapOperations#20]
Gradle build on https://jitpack.io is not availiable.
I've talked with jitpack support & they told me: 
"we don’t have NDK installed on the build servers"
also the issue was opened https://github.com/jitpack/jitpack.io/issues/24

BTW can you pls use another build system before they solve the problem?

**Comment by komissarovdenis** [comment]
Build log from jitpack server

dirname: missing operand
Try 'dirname --help' for more information.
Run gradle build
Gradle build script
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Getting list of gradle tasks
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
publishToMavenLocal task not found
install task not found
Gradle 'install' task not found. Please add the 'maven' or 'android-maven' plugin.
See the documentation and examples: https://github.com/jitpack/jitpack.io
LIBFILE=./JniBitmapOperationsLibrary/build.gradle
Found android library build file ./JniBitmapOperationsLibrary/build.gradle
Running: ./gradlew --daemon -Pgroup=com.github.AndroidDeveloperLB -Pversion=649796a926 install
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Trying again without wrapper
Download https://repo1.maven.org/maven2/com/github/dcendents/android-maven-plugin/1.2/android-maven-plugin-1.2.pom
Download https://repo1.maven.org/maven2/com/github/dcendents/android-maven-plugin/1.2/android-maven-plugin-1.2.jar
WARNING [Project: :JniBitmapOperationsLibrary] Current NDK support is deprecated.  Alternative will be provided in the future.
:JniBitmapOperationsLibrary:compileLint
:JniBitmapOperationsLibrary:copyReleaseLint UP-TO-DATE
:JniBitmapOperationsLibrary:mergeReleaseProguardFiles
:JniBitmapOperationsLibrary:buildNative FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':JniBitmapOperationsLibrary:buildNative'.
> A problem occurred starting process 'command 'null/ndk-build''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 24.3 secs
Done

**Comment by AndroidDeveloperLB** [comment]
what build system?
and what are those logs?
I'm not familiar with those things. I still struggle (and fail) to even import this old library to Android Studio. I have no idea how others did it. Sorry...

**Comment by komissarovdenis** [comment]
Those logs from jitpack build system about my request can't resolve dependency of your project
I don't know what build system they use. But just your project not compile due to NDK unsupport

**Comment by komissarovdenis** [comment]
And until they add NDK support for those build system nobody can't use 
dependencies {
    compile 'com.github.AndroidDeveloperLB:AndroidJniBitmapOperations:649796a926'
}

**Comment by AndroidDeveloperLB** [comment]
Sorry. I still don't understand what it means and how to use it.
I don't know how to help you.

**Comment by komissarovdenis** [comment]
It's was just notice for you link for your project from https://android-arsenal.com/details/1/1138
with Gradle dependency is invalid
And there is a need to change https://jitpack.io repository to something else

**Comment by AndroidDeveloperLB** [comment]
Again, I can't help with this issue. Sorry. I am not familiar with it and I don't have enough knowledge to do it currently.

**Comment by komissarovdenis** [comment]
ok, thanks

**Comment by AndroidDeveloperLB** [comment]
Should I close the issue? Or could others help you with this?

**Comment by komissarovdenis** [comment]
Yes, you could close it
