### ISSUE TITLE
Crashes on ART

### ISSUE THREAD

**Issue by higerra** [AndroidDeveloperLB/AndroidJniBitmapOperations#23]
Hi,
First thanks very much for this excellent library! This really solves my OOM issue.
This library will crash on ART, due to the tighter jni check rule. More specifically, we cannot pass 0 capacity to NewDirectByteBuffer() (around line 305 in JniBitmapOperationsLibrary.cpp).
I simply changed the capacity to 1 and it works. I'm not quite familiar with JNI, so you might better take a look yourself.

Hope this will help.

Best

**Comment by AndroidDeveloperLB** [comment]
Hi,
Sadly, even now I can't succeed importing my own library to Android-Studio, so it's very hard for me to fix things (even Eclipse started having issues).
However, now that I searched for this command ("NewDirectByteBuffer") , maybe I was wrong about how to use it? It was so long ago that I don't remember even what it is...
Can you please send me APKs of before and after this change? I also have Lollipop, and I remember it worked fine without this "1" value.

**Comment by higerra** [comment]
Well, I'm programming on a special device, so apk won't run on normal Android device.
Loading to Android Studio is pretty smooth on my side, the directory is as follows:
![screenshot from 2015-05-18 16 30 08](https://cloud.githubusercontent.com/assets/2343217/7690747/e5527e80-fd7b-11e4-8a0a-d22576bae4c0.png)
And add ndk.dir in local.properties, nothing special.

**Comment by AndroidDeveloperLB** [comment]
Can you please show a step-by-step way to import my sample&library, and be able to really edit C++ code and compile it on Android-Studio ?
No matter what I've tried - it didn't work.
About the APKs, I meant sending me the APKs of my own sample. Not yours.

**Comment by higerra** [comment]
Actually I couldn't get your sample work either... Seems that it cannot find the shared library.
For my own project, I just did the following steps:
1. Create a 'jni' folder under src/main/ folder and copy JniBitmapOprationsLibrary.cpp to this folder.
2. Add a package com.jni.bitmap_operations, and add JniBitmapHolder.java to this package.
3. Add your NDK path to local.properties
4. Import com.jni.bitmap_operations package where it will be used
And it should be fine, except the NewDirectBuffer issue on my side.

**Comment by AndroidDeveloperLB** [comment]
It didn't work now either. It says:

D:\android\ndk\build\core\add-application.mk
Error:(199) *** Android NDK: Aborting...    .  Stop.
Error:Execution failed for task ':app:compileDebugNdk'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'D:\android\ndk\ndk-build.cmd'' finished with non-zero exit value 2

I will try out the new NDK version (10e). Hope it will help.

**Comment by dinghu** [comment]
hi,i use your lib in my apication,but when load a large jpeg picture,it also stop with OOM, the picture is 5184x3456, how to load a bitmap like this?

**Comment by dinghu** [comment]
I repalce your test.png to a lager jpeg.

**Comment by AndroidDeveloperLB** [comment]
@dinghu This looks like a question that should be in a new thread.
Anyway, OOM will be avoided only if you succeed decoding using the normal way, use the library, recycle the previous bitmap, do the things you want, and then create a new bitmap from the library.

The input and output still needs to stay in the heap memory.
However, you can modify the code to handle a bitmap with 565 config, which uses only half the memory (yet without transparency support). 

Another solution is to avoid using this library, and use a different library instead, which allows you to decode the bitmap right inside JNI :
https://github.com/suckgamony/RapidDecoder
