### ISSUE TITLE
Load Bitmap from Uri or path file.

### ISSUE THREAD

**Issue by Marchrius** [AndroidDeveloperLB/AndroidJniBitmapOperations#27]
It's not an issue report.

How can I load a bitmap from a Uri or File path? There is a way to accomplish this with this library or not?
If not, there are a possibility to implement?

**Comment by AndroidDeveloperLB** [comment]
The library doesn't have this feature. It's in the TODO list ("decode the image directly within JNI, instead of giving it from the Java "world". This should be very handy.") , but because I don't have the time and knowledge for this, I might never add this. :(
In order to load bitmaps without Java, I need to know how to decode images from bytes (taken from files/uris), and this needs a lot of investigation because I don't think there is a built in JNI function for this.

**Comment by AndroidDeveloperLB** [comment]
But, if you succeed with this, please share it and put the code in the repo. It could be a very good feature.

**Comment by Marchrius** [comment]
I don't know If this can be "ok", but I've writed this. It runs on native code so It is faster than Java, but it uses native method from BitmapFactory.

```c
/**load java bitmap (from FileDescriptor data)*/ //
JNIEXPORT jobject JNICALL Java_com_jni_bitmap_1operations_JniBitmapHolder_jniStoreBitmapFromFileDescriptor(
        JNIEnv * env, jobject obj, jobject fileDescriptor, jobject rect, jobject options) {

  jclass bitmapFactoryCls = env->FindClass("android/graphics/BitmapFactory");
  jclass bitmapCls = env->FindClass("android/graphics/Bitmap");

  if (fileDescriptor == NULL) {
    LOGE("FileDescriptor is null !");
    return NULL;
  }

  jmethodID decodeFileDescriptorFunction = env->GetStaticMethodID(bitmapFactoryCls,
                                                                "nativeDecodeFileDescriptor",
                                                                "(Ljava/io/FileDescriptor;Landroid/graphics/Rect;Landroid/graphics/BitmapFactory$Options;)Landroid/graphics/Bitmap;");

  jmethodID recycleFunction = env->GetMethodID(bitmapCls, "recycle", "()V");

  if (decodeFileDescriptorFunction == NULL) {
    LOGE("decodeFileDescriptor not found");
    return NULL;
  }

  jobject bitmap = env->CallStaticObjectMethod(bitmapFactoryCls,
                                decodeFileDescriptorFunction,
                                fileDescriptor,
                                rect,
                                options);

  // LOGD("Loaded");
  jobject handler = Java_com_jni_bitmap_1operations_JniBitmapHolder_jniStoreBitmapData(env, obj, bitmap);

  // Recycle the bitmap to free memory
  env->CallVoidMethod(bitmap, recycleFunction);

  // Return handler (from jniStoreBitmapData)
  return handler;
}
```

Loaded one 4k image and reloaded many times other images on a 2 GB RAM device.

**Comment by AndroidDeveloperLB** [comment]
This won't help, because you call a Java function from JNI . It has the exact same speed and heap-memory restrictions as the normal Android API.

**Comment by Marchrius** [comment]
Yes, you are right. To accomplish all the operations on native side need to compile with SDK/NDK source code.

**Comment by AndroidDeveloperLB** [comment]
or implement by yourself, which could take a while...
