### ISSUE TITLE
Cannot get the sample to compile / run

### ISSUE THREAD

**Issue by ttsik** [AndroidDeveloperLB/AndroidJniBitmapOperations#28]
Hi, I am having issues compiling the sample. In particular, I am getting the following 

Error:Execution failed for task ':JniBitmapOperationsLibrary:compileReleaseNdk'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'E:\Android\android-ndk-r10e\ndk-build.cmd'' finished with non-zero exit value 2

Any ideas

Thanks

**Comment by AndroidDeveloperLB** [comment]
did you really download NDK ? and put it in the path that it talks about?

**Comment by AndroidDeveloperLB** [comment]
This works now on Android Studio. Closing it.
