### ISSUE TITLE
how to use it in AndroidStudio?

### ISSUE THREAD

**Issue by gepriniusce** [AndroidDeveloperLB/AndroidJniBitmapOperations#29]
how to use it in AndroidStudio?

**Comment by AndroidDeveloperLB** [comment]
install the NDK (I think via the plugins of the IDE), and then open the project.

**Comment by Voyz** [comment]
Following is what worked for me without using CMake, only ndkBuild.

1:
Copy contents of 
`LIBRARY_SOURCE/JniBitmapOperationsLibrary/jni/`
to
`YOUR_PROJECT/app/src/main/jni/`

and contents of:
`LIBRARY_SOURCE/JniBitmapOperationsLibrary/src/`
to
`YOUR_PROJECT/app/src/main/java/`

Important! Make sure you don't just copy the .java file to your project and change its package - the cpp library relies on the com.jni.bitmap_operations package - haven't tried changing the cpp itself to my project structure.

2:
Add following to build.gradle (app module, not project):
```
sourceSets {
        main {
            jni.srcDirs = []
            jniLibs.srcDir 'src/main/jni'
        }
    }
externalNativeBuild {
        ndkBuild {
            path 'src/main/jni/Android.mk'
        }
    }

defaultConfig{
 [other stuff from config...]

 ndk {
            moduleName "JniBitmapOperationsLibrary"
            ldLibs "log",  "jnigraphics"
            //optional: filter abis to compile for: abiFilters "x86", "armeabi-v7a"
            //otherwise it will compile for all abis: "armeabi", "armeabi-v7a", "x86", and "mips"
        }
}

```

3:
Add following to local.properties
`ndk.dir=PATH_TO_YOUR_NDK`
(ndk download here: https://developer.android.com/ndk/downloads/index.html )

**Comment by AndroidDeveloperLB** [comment]
Sorry I can't help you with any of those.
