### ISSUE TITLE
Is there any way to change CMYK to RGB color space of image using your library..?

### ISSUE THREAD

**Issue by ddpatel2606** [AndroidDeveloperLB/AndroidJniBitmapOperations#30]
Is there any way to change CMYK to RGB color space of image using your library..?

**Comment by AndroidDeveloperLB** [comment]
It doesn't have the code for it. You can add it if you wish, of course.
The library is quite minimal, and you can learn from it how to handle bitmaps within JNI. 
Also, do note that whatever you use in JNI, you must go back to RGB when returning the result to the Java world, as this is how bitmap data is stored in the Bitmap object.
