### ISSUE TITLE
Support for setPixels...

### ISSUE THREAD

**Issue by adanecito** [AndroidDeveloperLB/AndroidJniBitmapOperations#31]
Hi,
I wanted to say thanks for these examples. I need to set offset and stride via setPixels to flip an image. Is there some issue with this using your code? I tried that after the memory was locked and before it is unlocked but it crashes when I  execute. What I am doing is executing a glreadpixels call in my C code which flips the image and I need to reflip it before I use the bitmap. I hate to create another array to flip the image.
Thanks!

**Comment by AndroidDeveloperLB** [comment]
What exactly do you want to try?To flip the image?
It's not so different then what I did. 
You don't have to create a new array just to flip an image. A single pixel to store on the side is enough.

**Comment by adanecito** [comment]
Thanks for the very quick feedback. Once working I intend to donate to your efforts. Below is what I have so far. I have commented out some code I was working with and will clean up once when done.Flipping is easier if I set use the offset and stride of setpixels. Then for offset I set it to total pixel size of the screen minus the width and set the stride to -width. I have that working in java but for some reason as I mentioned it does not work.
I have not addressed byte order. In java I use ByteBuffer and set the order to native. I have included the method that I am trying to replicate that is in java also.
I also have code to convert bgra 8888 to argb 888 as you may notice.
Regards,-Tony

JNIEXPORT jobject JNICALL
Java_com_myuniportal_maps_layers_FilterLayer_getScreenshotJNI(
        JNIEnv *env,
        jobject obj, jint width, jint height) {
    int screenshotSize = width * height;

    //void* aa = malloc(screenshotSize * 4);
    //jobject bb = env->NewDirectByteBuffer(aa, screenshotSize * 4);

    //jclass ByteBufferClass = env->FindClass("java/nio/ByteBuffer");
   // jmethodID asIntBuffer_methodID = env->GetMethodID(ByteBufferClass, "asIntBuffer", "()Ljava/nio/IntBuffer;");

   // jmethodID order_methodID = env->GetMethodID(ByteBufferClass, "order", "(Ljava/nio/ByteOrder;)Ljava/nio/ByteBuffer;");

    //env->CallObjectMethod(bb, order_methodID, endian);
    //jobject pixelsBuffer = env->CallObjectMethod(bb,
     //                                                    asIntBuffer_methodID);

    uint32_t* result = new uint32_t[height * width]; // or GLfloat

    glReadPixels(0, 0, width, height, GL_RGBA, GL_UNSIGNED_BYTE, result);



    //int *pixelsBuffer = (int*)malloc(screenshotSize*4); //each pixel is 4 bytes argb
   // directBuffer.asIntBuffer().get(pixelsBuffer);
   // directBuffer=null; //??

    //jint *narr = env->GetIntArrayElements(pixelsBuffer, NULL);

    //bgra to argb
    for (int i = 0; i < screenshotSize; ++i) {
        // The alpha and green channels' positions are preserved while thered and blue are swapped
        result[i] = ((result[i] & 0xff00ff00)) | ((result[i] & 0x000000ff) << 16) | ((result[i] & 0x00ff0000) >> 16);
    }

    int offset = screenshotSize - width;
    int stride = -width;
    int distance = 0;
    uint32_t tempPixel1 = 0;
    uint32_t tempPixel2 = 0;
    int counter = 0;
    //flip array back
    for (int i = offset; i < screenshotSize; i=i-width) {
        distance = offset + width;
        for(int j= i; j<distance; j++) {
            // The alpha and green channels' positions are preserved while thered and blue are swapped
            tempPixel1 = result[j];
            tempPixel2 = result[counter];
            //flip
            result[counter]=tempPixel1;
            result[j]=tempPixel2;
            counter++;
        }

    }

   // jclass bitmapConfig = env->FindClass("android/graphics/Bitmap$Config");
   // jfieldID rgba8888FieldID = env->GetStaticFieldID(bitmapConfig, "ARGB_8888", "Landroid/graphics/Bitmap$Config;");
   // jobject rgba8888Obj = env->GetStaticObjectField(bitmapConfig, rgba8888FieldID);

   // jclass bitmapClass = env->FindClass("android/graphics/Bitmap");
   // jmethodID createBitmapMethodID = env->GetStaticMethodID(bitmapClass,"createBitmap", "(IILandroid/graphics/Bitmap$Config;)Landroid/graphics/Bitmap;");
   // jobject bitmapObj = env->CallStaticObjectMethod(bitmapClass, createBitmapMethodID, width, height, rgba8888Obj);



    //////// create bitmap for the data
    jclass bitmapCls = env->FindClass("android/graphics/Bitmap");
    jmethodID createBitmapFunction = env->GetStaticMethodID(bitmapCls,
                                                           "createBitmap",
                                                           "(IILandroid/graphics/Bitmap$Config;)Landroid/graphics/Bitmap;");
    jstring configName = env->NewStringUTF("ARGB_8888");
    jclass bitmapConfigClass = env->FindClass("android/graphics/Bitmap$Config");
    jmethodID valueOfBitmapConfigFunction = env->GetStaticMethodID(
            bitmapConfigClass, "valueOf",
            "(Ljava/lang/String;)Landroid/graphics/Bitmap$Config;");
    jobject bitmapConfig = env->CallStaticObjectMethod(bitmapConfigClass,
                                                      valueOfBitmapConfigFunction, configName);
   jobject newBitmap = env->CallStaticObjectMethod(bitmapCls,
                                                    createBitmapFunction, width,
                                                   height, bitmapConfig); //stride and offset added to flip image back

   // jmethodID setPixelsMid = env->GetMethodID(bitmapCls, "setPixels", "([IIIIIII)V");
   // env->CallVoidMethod(newBitmap, setPixelsMid, result, screenshotSize-width, -width, 0, 0, width, height);
    //env->CallVoidMethod(newBitmap, setPixelsMid, result, 0, width, 0, 0, width, height);

    //
    // putting the pixels into the new bitmap:
    //
    int ret;
    void* bitmapPixels;
    if ((ret = AndroidBitmap_lockPixels(env, newBitmap, &bitmapPixels)) < 0)
    {
       // LOGE("AndroidBitmap_lockPixels() failed ! error=%d", ret);
        return NULL;
    }
    uint32_t* newBitmapPixels = (uint32_t*) bitmapPixels;
    int pixelsCount = height
                      * width;
    memcpy(newBitmapPixels, result,
           sizeof(uint32_t) * pixelsCount);

    AndroidBitmap_unlockPixels(env, newBitmap);

    return newBitmap;
}

public Bitmap getScreenshot(int viewportWidth,int viewportHeight) {
    
    int screenshotSize = viewportWidth * viewportHeight;

    ByteBuffer bb = ByteBuffer.allocateDirect(screenshotSize * 4);
    bb.order(ByteOrder.nativeOrder());

    GLES20.glReadPixels(0, 0, viewportWidth, viewportHeight, GLES20.GL_RGBA, GLES20.GL_UNSIGNED_BYTE, bb);

    int pixelsBuffer[] = new int[screenshotSize];
    bb.asIntBuffer().get(pixelsBuffer);
    bb=null;

    // Convert from RGBA_8888 (Which is actually ABGR as the whole buffer seems to be inverted) --> ARGB_8888
     for (int i = 0; i < screenshotSize; ++i) {
        // The alpha and green channels' positions are preserved while the      red and blue are swapped
        pixelsBuffer[i] = ((pixelsBuffer[i] & 0xff00ff00)) | ((pixelsBuffer[i] & 0x000000ff) << 16) | ((pixelsBuffer[i] & 0x00ff0000) >> 16);
    }

    //create bitmap then set pixels such that offset and stride flip the image vertically since read pixels flips it already
    Bitmap bitmap = Bitmap.createBitmap(viewportWidth, viewportHeight, Bitmap.Config.ARGB_8888);
    bitmap.setPixels(pixelsBuffer, screenshotSize - viewportWidth, -viewportWidth, 0, 0, viewportWidth, viewportHeight);
    
    return bitmap;
}
 

    On Tuesday, January 17, 2017 1:29 PM, AndroidDeveloperLB <notifications@github.com> wrote:
 

 What exactly do you want to try?To flip the image?
It's not so different then what I did.
You don't have to create a new array just to flip an image. A single pixel to store on the side is enough.—

**Comment by AndroidDeveloperLB** [comment]
Again, what are you trying to do?
And why do you call Java commands from JNI ? 
About donating, I'd prefer if you try and share my apps instead ([here](https://play.google.com/store/apps/developer?id=AndroidDeveloperLB))

**Comment by adanecito** [comment]
Good question. I am trying to improve the overall time to do a screenshot. That screenshot feeds into a filter that in turn the resulting texture goes back to the Android screen.

By using what I sent you I went from 500ms to 60ms but still more work to do yet.
I will look at your apps.
Mine are on google play and my popular mars Android app is "Mars Xplorer" I have a filter feature and if you decide to play with it you will understand why I am doing what I am doing.
Thanks,-Tony
 

    On Tuesday, January 17, 2017 2:05 PM, AndroidDeveloperLB <notifications@github.com> wrote:
 

 Again, what are you trying to do?
And why do you call Java commands from JNI ?
About donating, I'd prefer if you try and share my apps instead (here)—

**Comment by adanecito** [comment]
Here is the link to Mars Xplorer:
https://play.google.com/store/apps/details?id=com.myuniportal.android.apps.marsxplorer 

    On Tuesday, January 17, 2017 2:59 PM, Tony Anecito <adanecito@yahoo.com> wrote:
 

 Good question. I am trying to improve the overall time to do a screenshot. That screenshot feeds into a filter that in turn the resulting texture goes back to the Android screen.

By using what I sent you I went from 500ms to 60ms but still more work to do yet.
I will look at your apps.
Mine are on google play and my popular mars Android app is "Mars Xplorer" I have a filter feature and if you decide to play with it you will understand why I am doing what I am doing.
Thanks,-Tony
 

    On Tuesday, January 17, 2017 2:05 PM, AndroidDeveloperLB <notifications@github.com> wrote:
 

 Again, what are you trying to do?
And why do you call Java commands from JNI ?
About donating, I'd prefer if you try and share my apps instead (here)—

**Comment by AndroidDeveloperLB** [comment]
Yes, I tried it now.
Nice app, but it takes a long time to load the images, and to also navigate.
The filter is quite slow and can flicker. 
I don't think you should do it in JNI. Instead, use OpenGL or something.

**Comment by adanecito** [comment]
Thanks for the complement. Well, download is dependent upon if you use wifi or not and the images get cached so if gets faster second time you visit a location. They come from USGS and NOAA so distance and server usage at the time affect experience.Panning and zooming using my old LG G2, Nexus 7 and LG G4 is quite fast but of course that is  from the images being cached.

Yep, the I am improving the whole filter process. Was a low priority and only a few people have mentioned it but I am addressing it now.  I am surprised how well it fast it runs on the Android considering most desktops have much better video card capability.
I am using OpenGL ES 2.0 but from Java it uses JNI anyway so using the NDK and C has already shown great improvement and that is what you have seen in my code as a first attempt. Been a while since I worked with C but will get better over time again. :-)

I may not use Bitmap.setPixels since I am rewriting the bgrA to argb loop to include the reverse the image flip that glreadpixels does. I may eliminate that since I run the bitmaps through Renderscript and will eventually eliminate that.

Again, thanks for the feedback and support I know you are busy. I will try your apps tonight when I take a break.

-Tony
 

    On Tuesday, January 17, 2017 3:15 PM, AndroidDeveloperLB <notifications@github.com> wrote:
 

 Yes, I tried it now.
Nice app, but it takes a long time to load the images, and to also navigate.
The filter is quite slow and can flicker.
I don't think you should do it in JNI. Instead, use OpenGL or something.—

**Comment by AndroidDeveloperLB** [comment]
I have Nexus 5x and I run on Wifi with max of 100Mbps.
The UI is slow in panning, meaning that I have to drag-touch a lot to move.
About OpenGL and advanced C/C++, sorry, I can't help. I use Java most of the time. This was a small library I've made to see what I can do with bitmaps on JNI.

**Comment by adanecito** [comment]
Ok I downloaded your apps and they are nice utilities. How long has it been available?
I finished my first pass of replacing that java method  and is slightly over 5x faster. Nice improvement thanks for the help.
Now just need to find or write a function for caching to native memory some java objects rather than the heap.
Thanks!
-Tony
 

    On Tuesday, January 17, 2017 4:08 PM, AndroidDeveloperLB <notifications@github.com> wrote:
 

 I have Nexus 5x and I run on Wifi with max of 100Mbps.
The UI is slow in panning, meaning that I have to drag-touch a lot to move.
About OpenGL and advanced C/C++, sorry, I can't help. I use Java most of the time. This was a small library I've made to see what I can do with bitmaps on JNI.—

**Comment by AndroidDeveloperLB** [comment]
Can you perhaps create a new Github repo (with sample) for just the screenshot?
It could be a nice thing to be able to take a screenshot faster than the normal API...
Does the screenshot work in a global way, meaning it can be taken even outside of the app ?

**Comment by adanecito** [comment]
Hi,If they use the NDK and Android Bitmap it should work but it is still Android NDK dependent. Not sure it is worth the effort to setup a Github account for that though. It is also integrated with the Android Studio which might be a problem for others.
Regards,-Tony
 

    On Tuesday, January 17, 2017 11:26 PM, AndroidDeveloperLB <notifications@github.com> wrote:
 

 Can you perhaps create a new Github repo (with sample) for just the screenshot?
It could be a nice thing to be able to take a screenshot faster than the normal API...
Does the screenshot work in a global way, meaning it can be taken even outside of the app ?—

**Comment by adanecito** [comment]
I found a faster way to do it but only pieces of it just like what I did. I also will remove the BitMap code and run it into C or C++ filters to get closer to real-time. But I have another issue to deal with first.
Thanks for the suggestion though.-Tony
 

    On Wednesday, January 18, 2017 9:12 AM, Tony Anecito <adanecito@yahoo.com> wrote:
 

 Hi,If they use the NDK and Android Bitmap it should work but it is still Android NDK dependent. Not sure it is worth the effort to setup a Github account for that though. It is also integrated with the Android Studio which might be a problem for others.
Regards,-Tony
 

    On Tuesday, January 17, 2017 11:26 PM, AndroidDeveloperLB <notifications@github.com> wrote:
 

 Can you perhaps create a new Github repo (with sample) for just the screenshot?
It could be a nice thing to be able to take a screenshot faster than the normal API...
Does the screenshot work in a global way, meaning it can be taken even outside of the app ?—

**Comment by AndroidDeveloperLB** [comment]
Please try to make a github repo for this. Could be handy.
