### ISSUE TITLE
Question about decode bitmap

### ISSUE THREAD

**Issue by kylin17** [AndroidDeveloperLB/AndroidJniBitmapOperations#33]
How to decode the image directly use native code to avoid memory jitter?

**Comment by AndroidDeveloperLB** [comment]
Sadly this library doesn't have this feature.
You can try other libraries that do it:
https://github.com/AndroidDeveloperLB/AndroidJniBitmapOperations#similar-libraries

**Comment by AndroidDeveloperLB** [comment]
@kylin17 This might allow to decode bitmaps in JNI:
https://developer.android.com/ndk/guides/image-decoder

**Comment by kylin17** [comment]
@AndroidDeveloperLB Thank you for your help. 👍

**Comment by AndroidDeveloperLB** [comment]
@kylin17 If you know how to use it and succeeded, please let me know.
I wonder if such a code could be useful here too, at least for Android 11.
