### ISSUE TITLE
Issue with free method?

### ISSUE THREAD

**Issue by jford2505** [AndroidDeveloperLB/AndroidJniBitmapOperations#34]
I'm no expert on JNI (or C++), but I had a concern about the jniFreeBitmapData function.

It seems that it doesn't free the jniBitmap object if  _storedBitmapPixels is NULL. I rewrote as follows:

    JNIEXPORT void JNICALL Java_com_jni_bitmap_1operations_JniBitmapHolder_jniFreeBitmapData(
	JNIEnv * env, jobject obj, jobject handle)
    {
    JniBitmap* jniBitmap = (JniBitmap*) env->GetDirectBufferAddress(handle);
    if (jniBitmap == NULL)
        return;
    if (jniBitmap->_storedBitmapPixels != NULL) {
        delete[] jniBitmap->_storedBitmapPixels;
        jniBitmap->_storedBitmapPixels = NULL;
    }
    delete jniBitmap;
    }

(Also wondering if there is any reason why you include jni.h twice?)

**Comment by AndroidDeveloperLB** [comment]
` jni.h` twice - probably a copy-paste mistake.

About the freeing, I have created this library a long time ago. I don't remember how it works. Have you tested what you wrote well enough? Does it work well even with the sample?
