### ISSUE TITLE
Fix the bug of having Aliasing when scaling down an image using Bilinear Interpolation

### ISSUE THREAD

**Issue by hjm1fb** [AndroidDeveloperLB/AndroidJniBitmapOperations#41]
I have fixed the bug of having Aliasing when scaling down an image using Bilinear Interpolation at certain rates like 0.6.
See pull Request: [Amend the wrong data index of ScaleBIBitmap method](https://github.com/AndroidDeveloperLB/AndroidJniBitmapOperations/pull/40#issue-340428877)

**Comment by AndroidDeveloperLB** [comment]
Please continue the talk there.
