### ISSUE TITLE
Crash | UnsatisfiedLinkError | couldn't find "libJniBitmapOperationsLibrary.so"

### ISSUE THREAD

**Issue by LiorA1** [AndroidDeveloperLB/AndroidJniBitmapOperations#45]
Hi,
I'm trying to work with the library, but it carshes when I'm trying to call:
JniBitmapHolder jniBitmapHolder = new JniBitmapHolder();

It can be the Architecture ?
Mine is AArch64 / arm64-v8a.

Any help will be appreciated !

Thank you !

StackTrace -
2020-05-13 22:43:47.690 6841-6927/com.example.camera2app E/AndroidRuntime: FATAL EXCEPTION: Camera2Thread
    Process: com.example.camera2app, PID: 6841
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.camera2app-OY-F6Bi4RdzSpscSZm7zRg==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.camera2app-OY-F6Bi4RdzSpscSZm7zRg==/lib/arm64, /data/app/com.example.camera2app-OY-F6Bi4RdzSpscSZm7zRg==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]] couldn't find "libJniBitmapOperationsLibrary.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.example.camera2app.JniBitmapHolder.<clinit>(JniBitmapHolder.java:17)

**Comment by LiorA1** [comment]
I followed option 2:
https://github.com/AndroidDeveloperLB/AndroidJniBitmapOperations#option-2

**Comment by LiorA1** [comment]
Solved by erasing the instructions in option 2.
with the help of:
https://stackoverflow.com/a/52894301/3790620

**Comment by AndroidDeveloperLB** [comment]
Sorry. The repository is very old. Instructions are probably wrong now.
If you can, please offer a PR that is updated. I have no idea today how to use my own repository :(

**Comment by LiorA1** [comment]
I managed to solve the first issue, as [explained ](https://github.com/AndroidDeveloperLB/AndroidJniBitmapOperations/issues/45#issuecomment-628836708)

Now the cpp file full in two errors:
"Incorrect type for parameter 'prarmeterName', which should have type 'jint'
And 
"Add extern 'C'"

Will open  a question in StackOverflow, maybe someone will assist.

**Comment by AndroidDeveloperLB** [comment]
Sorry for that. :(

**Comment by LiorA1** [comment]
It's okay..
I solved the issue, with assist: 
https://stackoverflow.com/questions/61807285/android-studio-cpp-file-errors-error-undefined-reference-to-androidbitmap-un

Any chance you looking at my new sample (that is working) for functionality check ?
Here:
https://github.com/LiorA1/MyRevApp

You also can update with your Repo..
