### ISSUE TITLE
Save a Bitmap as a Byte array or image File

### ISSUE THREAD

**Issue by jcastrov** [AndroidDeveloperLB/AndroidJniBitmapOperations#6]
Your algorithm helps me a lot saving memory in my app, Thank you; I used your algorithm like this:

``` java
public Bitmap getRotatedBitmap(Bitmap bitmap)
{
    JniBitmapHolder bitmapHolder = new JniBitmapHolder();
    bitmapHolder.storeBitmap(bitmap);
    bitmapHolder.rotateBitmapCw90();
    bitmap.recycle();
    return bitmapHolder.getBitmapAndFree();
}
```

Now, the next step is save this bitmap without lose quality. I'll try this: 

``` java
public void saveBitmap1(Bitmap bitmap)
{
    bitmap = getRotatedBitmap(bitmap);
    String name = "desiredFilename.png";
    FileOutputStream fos = openFileOutput(name, Context.MODE_PRIVATE);
    bitmap.compress(Bitmap.CompressFormat.PNG, 100, fos);
    fos.flush();
    fos.close();
}
```

The algorithm works fine, but this is too slow when the bitmap is compressing in PNG or WEBP. JPEG with 100 quality it's faster, anyway, the bitmap will lost quality. I'll try this too

``` java
public void saveBitmap2(Bitmap bitmap)
{
    bitmap = getRotatedBitmap(bitmap);
    int bytes = bitmap.getByteCount();
    ByteBuffer buffer = ByteBuffer.allocate(bytes);
    bitmap.copyPixelsToBuffer(buffer);
    byte[] array = buffer.array();
    String name = "desiredFilename.png";
    FileOutputStream fos = openFileOutput(name, Context.MODE_PRIVATE);
    fos.write(array);
    fos.flush();
    fos.close();
}
```

This solution have problems with big bitmaps, i.e. 5312 x 2988. When the buffer is allocating the bytes throws an OutOfMemoryException. And I can't resize the picture; I must rotate the picture without resize or lost quality.

So, Is there a form to get a byte array from your native library? Or Could you help me how I can save the bitmap as a File, avoiding memory exceptions?

I'll be very grateful if you can solve my problem

**Comment by ali1995reza** [comment]
Hi guys . I need to save 2 bitmaps into just one Image file and show them in the file , please if any onw know how i can do it help me . more description here : http://stackoverflow.com/questions/39028509/android-save-2-bitmap-into-just-one-image-file?noredirect=1#comment65421469_39028509

**Comment by AndroidDeveloperLB** [comment]
@ali1995reza First, you should create a new thread.
Second, if you got a solution, why ask about it here?
Third, this project is for JNI handling of bitmaps. If you wish, you can change the code inside, to create a new bitmap in JNI itself to combine the 2 bitmaps. You could even avoid having 2 bitmaps in memory at the same time, if you wish.

**Comment by ali1995reza** [comment]
But i never got solution . I have a big view over than 10000×10000 pixels and i want to save it to an Image file . I must create bitmap from part of this and then save dat ! Because of this size i never cant create a bitmap for entire of view . Hoe i can do it ?

**Comment by AndroidDeveloperLB** [comment]
OK, I answered there. Please avoid writing in existing threads.
